name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "18:00"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.gustmdqkr321 }}
      - name: Commit & Push
        run: |
          git config user.name gustmdqkr321
          git config user.email mbc3940@kookmin.ac.kr
          git add -A .
          git commit -m "generated"
          git push
